Workshop_Petstagram/petstagram_project/petstagram_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petstagram_project.common.urls')),
    path('accounts/', include('petstagram_project.accounts.urls')),
    path('pets/', include('petstagram_project.pets.urls')),
    path('photos/', include('petstagram_project.photos.urls')),
]

Workshop_Petstagram/petstagram_project/petstagram_project/photos/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.db import models

from petstagram_project.pets.models import Pet
from petstagram_project.photos.validators import image_size_validator

# Create your models here.

# The field Photo is required:
# • Photo - the user can upload a picture from storage, the maximum size of the photo can be 5MB
# The fields description and tagged pets are optional:
# • Description - a user can write any description of the photo; it should consist of a maximum of 300 characters
# and a minimum of 10 characters
# • Location - it should consist of a maximum of 30 characters
# • Tagged Pets - the user can tag none, one, or many of all pets. There is no limit on the number of tagged pets
# There should be created one more field that will be automatically generated:
# • Date of publication - when a picture is added or edited, the date of publication is automatically generated

UserModel = get_user_model()


class Photo(models.Model):
    # pet_image = models.ImageField(
    #     blank=False,
    #     null=False,
    #     validators=(image_size_validator,),
    #     upload_to='mediafiles/photos'
    # )

    description = models.TextField(
        max_length=300,
        validators=(MinLengthValidator(10),),
        blank=True,
        null=True
    )
    location = models.CharField(max_length=30, blank=True, null=True)
    tagged_pets = models.ManyToManyField(Pet, blank=True)
    date_of_publication = models.DateField(
        auto_now=True,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.DO_NOTHING,
    )

    def __str__(self):
        return f'{self.pk} - {self.pet_image}'

Workshop_Petstagram/petstagram_project/templates/login-page.html
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet"
          href="/static/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/static/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/static/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">

                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Login Page -->
                        <a href="#">
                            <i>Login</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Register Page -->
                        <a href="">
                            <i>Register</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>

    <!-- Start Login Section-->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Login Form-->
            <form action="#">
                <p>
                    <label for="id_username">Username:</label>
                    <input type="text" placeholder="Username">
                </p>
                <p>
                    <label for="id_password">Password:</label>
                    <input type="password" placeholder="Password">
                </p>

                <!-- Login Button-->
                <button type="submit">Log in</button>
            </form>
            <!-- End Login Form -->

        </div>
        <div class="second-option">

            <!-- Link to Register Page-->
            <p>Don't have account? <a href="#">Register</a></p>
        </div>
    </div>
    <!-- End Login Section-->

</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2022 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>

Workshop_Petstagram/petstagram_project/templates/pet-add-page.html
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet"
          href="/static/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/static/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>

</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/static/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">
                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Profile Page -->
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>

    <!-- Start Add Pet Section-->
    <div class="edit-delete edit-photo">
        <h2>Add pet</h2>

        <!-- Start Add Pet Form -->
        <form action="#">
            <p>
                <label for="pet-name">Pet name: </label>
                <input type="text" placeholder="Pet name">
            </p>
            <p>
                <label for="pet-date">Date of birth: </label>
                <input type="date">
            </p>
            <p>
                <label for="pet-image">Link to image: </label>
                <input type="text" placeholder="Link to image">
            </p>
            <!-- Add Pet Button -->
            <button class="add-btn" type="submit">Add Pet</button>
        </form>
        <!-- End Add Pet Form -->

    </div>
    <!-- End Add Pet Section -->

</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2022 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>

Workshop_Petstagram/petstagram_project/templates/pet-delete-page.html
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet"
          href="/static/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/static/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/static/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">
                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Profile Page -->
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>
    <!-- Starts Delete Pet Section -->
    <div class="edit-delete edit-photo">
        <h2>Delete pet</h2>
        <!-- Starts Delete Pet Form -->
        <form action="#">
            <p>
                <label for="pet-name">Pet name: </label>
                <input type="text" placeholder="Name" value="Sasho" disabled>
            </p>
            <p>
                <label for="pet-date">Date of birth: </label>
                <input type="date" disabled>
            </p>
            <p>
                <label for="pet-image">Link to image: </label>
                <input type="text" placeholder="Link to image"
                       value="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631"
                       alt="pet image" disabled>
            </p>
            <!-- Delete Pet Button -->
            <button class="delete-btn" type="submit">Delete</button>
            <!-- Go Back Button -->
            <a class="btn btn-primary" href="javascript:history.back()">
                <button class="edit-btn" type="button">Go back</button>
            </a>
        </form>
        <!-- End Delete Pet Form -->
    </div>
    <!-- End Delete Pet Section -->
</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2022 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>

Workshop_Petstagram/petstagram_project/templates/pet-edit-page.html
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet"
          href="/static/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/static/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/static/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">
                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Profile Page -->
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>
    <!-- Start Edit Pet Section -->
    <div class="edit-delete edit-photo">
        <h2>Edit Pet</h2>
        <!-- Start Edit Pet From -->
        <form action="">
            <p>
                <label for="pet-name">Pet name: </label>
                <input type="text" placeholder="Name" value="Sasho">
            </p>
            <p>
                <label for="pet-date">Date of birth: </label>
                <input type="date">
            </p>
            <p>
                <label for="pet-image">Link to image: </label>
                <input type="text" placeholder="Link to image"
                       value="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631"
                       alt="pet image">
            </p>
            <!-- Edit Pet Button -->
            <button class="edit-btn" type="submit">Edit</button>
        </form>
        <!-- End Edit Pet Form -->

    </div>
    <!-- End Edit Pet Section -->

</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2022 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>

Workshop_Petstagram/petstagram_project/templates/photo-add-page.html
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet"
          href="/static/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/static/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/static/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">
                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Profile Page -->
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>
    <!-- Start Add Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Add photo</h2>
        <!-- Start Add Photo Form -->
        <form action="" enctype="multipart/form-data">
            <p>
                <label for="id_photo_file">Photo file:</label>
                <input type="file">
            </p>

            <p>
                <label for="id_description">Description:</label>
                <input type="text">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>
            <!-- Add Photo Button -->
            <button class="add-btn" type="submit">Add Photo</button>
        </form>
        <!-- End Add Photo Form -->
    </div>
    <!-- End Add Photo Section -->
</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2022 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>

Workshop_Petstagram/petstagram_project/templates/photo-edit-page.html
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet"
          href="/static/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/static/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/static/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">
                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Profile Page -->
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>

    <!-- Starts Edit Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Edit photo</h2>

        <!-- Starts Edit Photo Form -->
        <form action="">
            <p>
                <label for="id_photo_file">Photo file:</label>
                <input type="file">
            </p>

            <p>
                <label for="id_description">Description:</label>
                <input type="text" value="Sasho is an Axolotl">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location"
                       value="Bansko, Bulgaria">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option selected>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>

            <!-- Edit Photo Button -->
            <button class="edit-btn" type="submit">Edit Photo</button>
        </form>
        <!-- End Edit Photo Form -->

    </div>
    <!-- End Edit Photo Section -->

</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2022 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>

Workshop_Petstagram/petstagram_project/templates/profile-delete-page.html
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet"
          href="/static/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/static/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/static/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">
                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Profile Page -->
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>

    <!-- Start Delete Profile Section -->
        <div class="delete-profile">
            <h1>
                Are you sure you want to delete your profile?
            </h1>
            <div class="sure-buttons">
                <!-- Yes (Delete Profile) Button -->
                <button>Yes</button>
                <!-- Go Back Button -->
                <a class="edit-btn" href="javascript:history.back()">Go Back</a>
            </div>
            <img src="/static/images/are_you_sure_cat.gif" alt="are you sure cat git">
        </div>
    <!-- End Delete Profile Section -->

</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2022 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>

Workshop_Petstagram/petstagram_project/templates/profile-edit-page.html
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet"
          href="/static/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/static/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/static/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">
                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Profile Page -->
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>
    <!-- Start Edit Profile Section -->
    <div class="edit-delete">
        <h2>Edit Profile</h2>
        <!-- Start Edit Profile From -->
        <form action="">
            <div class="label-input">
                <label for="first name">First name: </label>
                <input type="text" placeholder="First name" value="Diyan">
            </div>
            <br>
            <div class="label-input">
                <label for="last name">Last name: </label>
                <input type="text" placeholder="Last name" value="Kalayadzhiev">
            </div>
            <br>
            <div class="label-input">
                <label for="username">Username: </label>
                <input type="text" placeholder="Username" value="k_dido">
            </div>
            <br>
            <div class="label-input">
                <label for="email">Email: </label>
                <input type="email" placeholder="Email" value="d.denov@gmail.com">
            </div>
            <br>
            <div class="label-input">
                <label for="image">Image: </label>
                <input type="text" placeholder="Link to to profile picture"
                       value="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631">
            </div>
            <br>

            <div class="label-input">
                <label for="image">Gender: </label>
                <div class="list-choice">
                    <div class="list-choice-title">Gender</div>
                    <div class="list-choice-objects">
                        <label>
                            <input type="radio" name="gender"/> <span>Male</span>
                        </label>
                        <label>
                            <input type="radio" name="gender"/> <span>Female</span>
                        </label>
                        <label>
                            <input type="radio" name="gender"/> <span>Do not show</span>
                        </label>
                    </div>
                </div>
            </div>

            <!-- Edit Profile Button -->
            <button class="edit-btn" type="submit">Edit</button>
        </form>
        <!-- End Edit Profile Form -->

    </div>
    <!-- End Edit Profile Section -->

</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2022 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>

Workshop_Petstagram/petstagram_project/templates/register-page.html
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet"
          href="/static/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/static/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/static/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">

                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Login Page -->
                        <a href="#">
                            <i>Login</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Register Page -->
                        <a href="">
                            <i>Register</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>

    <!-- Start Register Section -->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Register Form -->
            <form action="">
                <input type="text" placeholder="Username">

                <input type="email" placeholder="Email">

                <input type="password" placeholder="Password">

                <input type="password" placeholder="Repeat Password">

                <!-- Register Button -->
                <button type="submit">Register</button>
            </form>
            <!-- End Register Form -->

        </div>
        <div class="second-option">

            <!-- Link to Login Page -->
            <p>Have an account? <a href="#">Log in</a></p>
        </div>
    </div>
    <!-- End Register Section -->

</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2022 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>